name: skg_hagen
description: The App for the Evangelisch-lutherische Stadtkirchengemeinde Hagen, Germany

version: 1.3.2+16

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  intl: ^0.18.1
  url_launcher: ^6.1.8
  yaml: ^3.1.1
  dio: ^4.0.6
  dio_http_cache: ^0.3.0
  map_launcher: any
  firebase_crashlytics: ^3.0.17
  shared_preferences: ^2.0.17
  flutter_html: ^2.2.1
  flutter_dotenv: ^5.0.2
  html: ^0.15.1
  add_2_calendar: ^2.1.3
  flutter_slidable: ^1.3.2
  share: ^2.0.4
  permission_handler: ^10.2.0
  file_utils: ^1.0.1
  path_provider: ^2.0.11
  open_file: ^3.0.1
  package_info: ^2.0.2
  firebase_remote_config: ^3.0.15
  launch_review: ^3.0.1
  firebase_messaging: ^14.3.0
  flutter_local_notifications: ^9.0.4
  firebase_analytics: ^10.1.6
  firebase_core : ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  mockito: ^5.0.15
  http_mock_adapter: ^0.3.3

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    #Config
    - .env
    - assets/config/
    #Icons
    - assets/images/icon/
    #Images
    - assets/images/
    #Text
    - assets/text/
  fonts:
    - family: Optima
      fonts:
        - asset: assets/fonts/Optima.ttc

#hive -> persistence