#The name of your workflow.
name:  Test, build and deploy
# Trigger the workflow on push or pull request
on: [push,pull_request]
#A workflow run is made up of one or more jobs. Jobs run in parallel by default.
jobs:

  build:
    name: populate variable
    runs-on: ubuntu-latest
    steps:
      - name: Printing work dir
        run: echo pwd

      - name: Build site assets
          working-directory: ${{ github.workspace }}
          run: ls -la
