#The name of your workflow.
name:  Test, build and deploy
# Trigger the workflow on push or pull request
on: [push,pull_request]
#A workflow run is made up of one or more jobs. Jobs run in parallel by default.
jobs:
#pwd: /home/runner/work/skg-hagen/skg-hagen
  build:
    name: populate variable
    runs-on: ubuntu-latest
    steps:
      - name: populating .env
        # defining variables
        env:
          - API: ${{ secrets.API }}
        run: |
          # set up .env
          echo "populating .env"
          cat >> ".env" <<EOF
          USERNAME = user
          PASSWORD = secret
          API = $API
          EOF
          shell: bash
      - name:
        # defining variables
        env:
          - GITHUB_WORKSPACE: ${{ GITHUB_WORKSPACE }}
          - CM_KEYSTORE: ${{ secrets.CM_KEYSTORE }}
          - CM_KEYSTORE_PASSWORD: ${{ secrets.CM_KEYSTORE_PASSWORD }}
          - CM_KEY_ALIAS_PASSWORD:  ${{ secrets.CM_KEY_ALIAS_PASSWORD }}
          - CM_KEY_ALIAS_USERNAME: ${{ secrets.CM_KEY_ALIAS_USERNAME }}
        run: |
        # set up key.properties
        echo "setting up key.properties"
        cat $CM_KEYSTORE | base64 --decode > tmp/keystore.keystore
        cat >> "$GITHUB_WORKSPACE/android/key.properties" <<EOF
        storePassword=$CM_KEYSTORE_PASSWORD
        keyPassword=$CM_KEY_ALIAS_PASSWORD
        keyAlias=$CM_KEY_ALIAS_USERNAME
        storeFile=tmp/keystore.keystore
        EOF
        shell: bash
