name:  Test, build and deploy
on: [push,pull_request]
jobs:
  file_setup:
    name: file/folder setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: populating .env
        env:
          APP_API: ${{ secrets.API }}
        run: |
          # set up .env
          echo "populating .env"
          cat > ".env" <<EOF
          USERNAME = user
          PASSWORD = secret
          API = $APP_API
          EOF
        shell: bash

      - name: creating temporal keystore file
        uses: finnp/create-file-action@1.0.0
        env:
          FILE_NAME: /tmp/keystore.keystore
          FILE_DATA: ''
      - name: creating android key.properties file
        uses: finnp/create-file-action@1.0.0
        env:
          FILE_NAME: android/key.properties
          FILE_DATA: "storePassword=KEYSTORE_PASSWORD
          keyPassword=KEY_ALIAS_PASSWORD
          keyAlias=KEY_ALIAS_USERNAME
          storeFile=/tmp/keystore.keystore"

      - name: populating android key.properties file
        env:
          CM_KEYSTORE: ${{ secrets.CM_KEYSTORE }}
          CM_KEYSTORE_PASSWORD: ${{ secrets.CM_KEYSTORE_PASSWORD }}
          CM_KEY_ALIAS_PASSWORD:  ${{ secrets.CM_KEYSTORE_PASSWORD }}
          CM_KEY_ALIAS_USERNAME: ${{ secrets.CM_KEY_ALIAS_USERNAME }}
        run: |
          # set up key.properties
          echo "setting up key.properties"
          echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.keystore
          sed -i "s/KEYSTORE_PASSWORD/$CM_KEYSTORE_PASSWORD/g" android/key.properties
          sed -i "s/KEY_ALIAS_PASSWORD/$CM_KEY_ALIAS_PASSWORD/g" android/key.properties
          sed -i "s/KEY_ALIAS_USERNAME/$CM_KEY_ALIAS_USERNAME/g" android/key.properties
        shell: bash

      - name: creating android local.properties file
        uses: finnp/create-file-action@1.0.0
        env:
          FILE_NAME: android/local.properties
          FILE_DATA: "flutter.sdk=HOME/programs/flutter"

      - name: setting up android local.properties file
        run: |
          # set up local.properties
          echo "setting up local.properties"
          sed -i "s/HOME/$HOME/g" android/local.properties
        shell: bash

      - name: validate input
        run: |
          cat android/key.properties
          cat android/local.properties
          du -sh /tmp/keystore.keystore
          wc /tmp/keystore.keystore
        shell: bash
