name:  Test, build and deploy
on: [push,pull_request]
jobs:
  file_setup:
    name: file/folder setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: populating .env
        env:
          APP_API: ${{ secrets.API }}
        run: |
          # set up .env
          echo "populating .env"
          cat > ".env" <<EOF
          USERNAME = user
          PASSWORD = secret
          API = $APP_API
          EOF
        shell: bash

      - name: populating android key.properties file
        env:
          CM_KEYSTORE: ${{ secrets.CM_KEYSTORE }}
          CM_KEYSTORE_PASSWORD: ${{ secrets.CM_KEYSTORE_PASSWORD }}
          CM_KEY_ALIAS_PASSWORD:  ${{ secrets.CM_KEYSTORE_PASSWORD }}
          CM_KEY_ALIAS_USERNAME: ${{ secrets.CM_KEY_ALIAS_USERNAME }}
        run: |
          # set up key.properties
          echo "setting up key.properties"
          sudo echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.keystore
          # set up key.properties
          echo "populating key.properties"
          sudo cat > "android/key.properties" <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_ALIAS_PASSWORD
          keyAlias=$CM_KEY_ALIAS_USERNAME
          storeFile=/tmp/keystore.keystore
          EOF
        shell: bash

      - name: populating firebase files
        env:
          ANDROID_FIREBASE_SECRET: ${{ secrets.ANDROID_FIREBASE_SECRET }}
          IOS_FIREBASE_SECRET: ${{ secrets.IOS_FIREBASE_SECRET }}
        run: |
          sudo echo $ANDROID_FIREBASE_SECRET | base64 --decode > android/app/google-services.json
          sudo echo $IOS_FIREBASE_SECRET | base64 --decode > ios/Runner/GoogleService-Info.plist
          sudo echo "a2V5" | base64 --decode > example.md
        shell: bash

      - name: validate input
        run: |
          cat android/key.properties
          cat android/app/google-services.json
          cat ios/Runner/GoogleService-Info.plist
          echo -----------------example------------------
          cat example.md
        shell: bash