name:  Test, build and deploy
on: [push,pull_request]
jobs:
  file_setup:
    name: file/folder setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: populating .env
        env:
          APP_API: ${{ secrets.API }}
        run: |
          # set up .env
          echo "populating .env"
          cat > ".env" <<EOF
          USERNAME = user
          PASSWORD = secret
          API = $APP_API
          EOF
        shell: bash

      - name: creating temporal keystore file
        uses: finnp/create-file-action@1.0.0
        env:
          FILE_NAME: /tmp/keystore.keystore
          FILE_DATA: ''
      - name: creating android key.properties file
        uses: finnp/create-file-action@1.0.0
        env:
          FILE_NAME: android/key.properties
          FILE_DATA: "storePassword=KEYSTORE_PASSWORD
          keyPassword=KEY_ALIAS_PASSWORD
          keyAlias=KEY_ALIAS_USERNAME
          storeFile=/tmp/keystore.keystore"

      - name: populating android key.properties file
        env:
          CM_KEYSTORE: ${{ secrets.CM_KEYSTORE }}
          CM_KEYSTORE_PASSWORD: ${{ secrets.CM_KEYSTORE_PASSWORD }}
          CM_KEY_ALIAS_PASSWORD:  ${{ secrets.CM_KEYSTORE_PASSWORD }}
          CM_KEY_ALIAS_USERNAME: ${{ secrets.CM_KEY_ALIAS_USERNAME }}
        run: |
          # set up key.properties
          echo "setting up key.properties"
          echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.keystore
          sed -i "s/KEYSTORE_PASSWORD/$CM_KEYSTORE_PASSWORD/g" android/key.properties
          sed -i "s/KEY_ALIAS_PASSWORD/$CM_KEY_ALIAS_PASSWORD/g" android/key.properties
          sed -i "s/KEY_ALIAS_USERNAME/$CM_KEY_ALIAS_USERNAME/g" android/key.properties
        shell: bash

#      - name: validate input
#        run: |
#          cat android/key.properties
#          du -sh /tmp/keystore.keystore
#          wc /tmp/keystore.keystore
#        shell: bash

      - name: creating android firebase file
        uses: finnp/create-file-action@1.0.0
        env:
          FILE_NAME: android/app/google-services.json
          FILE_DATA: 'ANDROID_FIREBASE_SECRET'

      - name: creating ios firebase file
        uses: finnp/create-file-action@1.0.0
        env:
          FILE_NAME: ios/Runner/GoogleService-Info.plist
          FILE_DATA: 'IOS_FIREBASE_SECRET'

      - name: populating android and ios firebase files
        env:
          ANDROID_FIREBASE_SECRET: ${{ secrets.ANDROID_FIREBASE_SECRET }}
          IOS_FIREBASE_SECRET: ${{ secrets.IOS_FIREBASE_SECRET }}
        run: |
          echo "replacing ios and android firebase files"
          sed -i "s/ANDROID_FIREBASE_SECRET/$IOS_FIREBASE_SECRET | base64 --decode/g" android/app/google-services.json
          sed -i "s/IOS_FIREBASE_SECRET/$IOS_FIREBASE_SECRET | base64 --decode/g" ios/Runner/GoogleService-Info.plist
        shell: bash