#The name of your workflow.
name:  Test, build and deploy
# Trigger the workflow on push or pull request
on: [push,pull_request]
#A workflow run is made up of one or more jobs. Jobs run in parallel by default.
jobs:
#pwd: /home/runner/work/skg-hagen/skg-hagen
  build:
    name: populate variable
    runs-on: ubuntu-latest
    steps:
      - name: setting runner variables
        env:
          - API: ${{ secrets.API }}
          - ANDROID_FIREBASE_SECRET: ${{ secrets.ANDROID_FIREBASE_SECRET }}
          - IOS_FIREBASE_SECRET: ${{ secrets.IOS_FIREBASE_SECRET }}
          - CM_KEYSTORE: ${{ secrets.CM_KEYSTORE }}
          - CM_KEYSTORE_PASSWORD: ${{ secrets.CM_KEYSTORE_PASSWORD }}
          - CM_KEY_ALIAS_PASSWORD:  ${{ secrets.CM_KEY_ALIAS_PASSWORD }}
          - CM_KEY_ALIAS_USERNAME: ${{ secrets.CM_KEY_ALIAS_USERNAME }}

      - name: populate .env
        run: |
          # set up .env
          cat >> ".env" <<EOF
          USERNAME = user
          PASSWORD = secret
          API = $API
          EOF
        shell: bash

      - name: populate key.properties
        run: |
          # set up key.properties
          echo $CM_KEYSTORE | base64 --decode > tmp/keystore.keystore
          cat >> "android/key.properties" <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_ALIAS_PASSWORD
          keyAlias=$CM_KEY_ALIAS_USERNAME
          storeFile=tmp/keystore.keystore
          EOF
        shell: bash
