#The name of your workflow.
name:  Test, build and deploy
# Trigger the workflow on push or pull request
on: [push,pull_request]
#A workflow run is made up of one or more jobs. Jobs run in parallel by default.
jobs:
#pwd: /home/runner/work/skg-hagen/skg-hagen
  build:
    name: populate variable
    runs-on: ubuntu-latest
    steps:
      #- name: checkout
      #  uses: actions/checkout@v2
      - name: populating .env
        # defining variables
        env:
          APP_API: ${{ secrets.API }}
        run: |
          # set up .env
          echo "populating .env"
          cat > ".env" <<EOF
          USERNAME = user
          PASSWORD = secret
          API = $APP_API
          EOF
        shell: bash
      - name: creating keystore file
        uses: finnp/create-file-action@1.0.0
        env:
          FILE_NAME: /tmp/kystore.kystore
          FILE_DATA: ''
      - name: creating key.properties file
        uses: finnp/create-file-action@1.0.0
        env:
          CM_KEYSTORE_PASSWORD: ${{ secrets.CM_KEYSTORE_PASSWORD }}
          CM_KEY_ALIAS_PASSWORD:  ${{ secrets.CM_KEY_ALIAS_PASSWORD }}
          CM_KEY_ALIAS_USERNAME: ${{ secrets.CM_KEY_ALIAS_USERNAME }}
          FILE_NAME: android/key.properties
          FILE_DATA: "storePassword=$CM_KEYSTORE_PASSWORD\nkeyPassword=$CM_KEY_ALIAS_PASSWORD\nkeyAlias=$CM_KEY_ALIAS_USERNAME\nstoreFile=/tmp/kystore.kystore"

      - name: populating keys.properties file
        env:
          CM_KEYSTORE: ${{ secrets.CM_KEYSTORE }}
        run: |
          # set up key.properties
          echo "setting up key.properties"
          echo $CM_KEYSTORE | base64 --decode > /tmp/kystore.kystore
        shell: bash

      - name: validate input
        run: cat android/key.properties
